import {
    Briefcase,
    Building2,
    Cloud,
    Code,
    Coins,
    Cpu,
    Globe,
    HeartPulse,
    Landmark,
    Layout,
    Leaf,
    Lightbulb,
    Rocket,
    Shield,
    Smartphone,
    ShoppingCart,
    TrendingUp,
    Truck,
    Users,
    Zap,
    CreditCard,
    GraduationCap,
    Car,
    Sprout,
    Gamepad2,
    Plane,
    Utensils,
    Brain,
    Music,
    Wrench,
    Bike,
    Home,
    Wifi,
    Headphones,
    Wallet,
    Stethoscope,
    LucideIcon,
    HelpCircle,
    ShoppingBag,
    Clapperboard,
    Sun,
    Wind,
    Tractor,
    Gavel,
    Radio,
    Tv,
    Film,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
    // Core categories matching frontend
    "credit-card": CreditCard,
    "cloud": Cloud,
    "shopping-cart": ShoppingCart,
    "graduation-cap": GraduationCap,
    "heart-pulse": HeartPulse,
    "heart": HeartPulse,
    "car": Car,
    "rocket": Rocket,
    "sprout": Sprout,
    "building": Building2,
    "building2": Building2,
    "plane": Plane,
    "shield": Shield,
    "brain": Brain,
    "gamepad-2": Gamepad2,
    "gamepad2": Gamepad2,
    "utensils": Utensils,
    "truck": Truck,
    "landmark": Landmark,
    "music": Music,
    "briefcase": Briefcase,

    // Industry mappings
    "fintech": Wallet,
    "saas": Cloud,
    "e-commerce": ShoppingCart,
    "ecommerce": ShoppingCart,
    "edtech": GraduationCap,
    "healthtech": HeartPulse,
    "healthcare": Stethoscope,
    "mobility": Car,
    "d2c": ShoppingBag,
    "agritech": Tractor,
    "agriculture": Sprout,
    "proptech": Home,
    "real-estate": Building2,
    "travel": Plane,
    "hospitality": Utensils,
    "cybersecurity": Shield,
    "ai": Brain,
    "artificial-intelligence": Brain,
    "ml": Cpu,
    "energy": Zap,
    "cleantech": Leaf,
    "gaming": Gamepad2,
    "foodtech": Utensils,
    "logistics": Truck,
    "supply-chain": Truck,
    "govtech": Landmark,
    "media": Clapperboard,
    "entertainment": Film,
    "hr-tech": Users,
    "recruitment": Briefcase,

    // Additional icons
    "code": Code,
    "coins": Coins,
    "cpu": Cpu,
    "globe": Globe,
    "layout": Layout,
    "leaf": Leaf,
    "lightbulb": Lightbulb,
    "smartphone": Smartphone,
    "trending-up": TrendingUp,
    "users": Users,
    "zap": Zap,
    "wrench": Wrench,
    "bike": Bike,
    "home": Home,
    "wifi": Wifi,
    "headphones": Headphones,
    "wallet": Wallet,
    "stethoscope": Stethoscope,
    "help-circle": HelpCircle,
    "sun": Sun,
    "wind": Wind,
    "gavel": Gavel,
    "radio": Radio,
    "tv": Tv,
};

export function getIcon(name: string): LucideIcon {
    return iconMap[name.toLowerCase()] || HelpCircle;
}
